### PR TITLE
handling for content-package-next field

### PR DESCRIPTION
**Pull request by radutudor**

### CODE REVIEW

**Comment by kovacshuni** [comment]
Could you please add the new field in `api.md` documentation too? After that, CircleCI should run the _dredd_ check for the documentation and should pass.

**Comment by radutudor** [comment]
*dredd* is not failing at the moment in the circle build. It should, right?

**Comment by radutudor** [comment]
Ok, so it seems *dredd* uses *gravel.js* in order to validate the http repsonses. The existence of additional fields in a JSON response do not cause a validation error (see https://www.relishapp.com/apiary/gavel/docs/expectations/body-json-example, Extra key in real JSON body)

**Comment by radutudor** [comment]
Anyway, field added to `api.md`, still no *dredd* failures.

**Pull request merged**
